/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Facilities;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP_Owner
 */
public class BloodBank extends javax.swing.JFrame {
int old,total,id;
String dname,bgroup;
    /**
     * Creates new form BloodBank
     */
    public BloodBank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buy = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        group = new javax.swing.JComboBox();
        donate = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        group1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        A1 = new javax.swing.JCheckBox();
        A2 = new javax.swing.JCheckBox();
        B1 = new javax.swing.JCheckBox();
        B2 = new javax.swing.JCheckBox();
        O1 = new javax.swing.JCheckBox();
        AB1 = new javax.swing.JCheckBox();
        AB2 = new javax.swing.JCheckBox();
        O2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        count = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        buy.setAlwaysOnTop(true);
        buy.setMinimumSize(new java.awt.Dimension(400, 300));
        buy.getContentPane().setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registration No. of Patient");
        buy.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 30, 170, 30);
        buy.getContentPane().add(pid);
        pid.setBounds(200, 30, 170, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Blood Group");
        buy.getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 160, 30);
        buy.getContentPane().add(pname);
        pname.setBounds(200, 70, 170, 30);

        jButton4.setFont(new java.awt.Font("Andalus", 0, 18));
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("BUY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        buy.getContentPane().add(jButton4);
        jButton4.setBounds(160, 200, 70, 40);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Name of Buyer");
        buy.getContentPane().add(jLabel5);
        jLabel5.setBounds(14, 70, 160, 30);

        group.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        buy.getContentPane().add(group);
        group.setBounds(240, 120, 60, 30);

        donate.setAlwaysOnTop(true);
        donate.setMinimumSize(new java.awt.Dimension(400, 300));
        donate.getContentPane().setLayout(null);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Donor's Name");
        donate.getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 20, 100, 40);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Blood Group");
        donate.getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 90, 100, 40);
        donate.getContentPane().add(name);
        name.setBounds(200, 30, 110, 30);

        group1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        donate.getContentPane().add(group1);
        group1.setBounds(230, 90, 60, 40);

        jButton5.setFont(new java.awt.Font("Andalus", 0, 18));
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Donate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        donate.getContentPane().add(jButton5);
        jButton5.setBounds(140, 170, 90, 50);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 140, 110);

        buttonGroup1.add(A1);
        A1.setText("A+");
        A1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        getContentPane().add(A1);
        A1.setBounds(1030, 160, 41, 20);

        buttonGroup1.add(A2);
        A2.setText("A-");
        A2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        getContentPane().add(A2);
        A2.setBounds(1030, 200, 37, 20);

        buttonGroup1.add(B1);
        B1.setText("B+");
        B1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1);
        B1.setBounds(1100, 160, 39, 20);

        buttonGroup1.add(B2);
        B2.setText("B-");
        B2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2);
        B2.setBounds(1100, 200, 40, 20);

        buttonGroup1.add(O1);
        O1.setText("O+");
        O1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        O1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O1ActionPerformed(evt);
            }
        });
        getContentPane().add(O1);
        O1.setBounds(1250, 160, 41, 20);

        buttonGroup1.add(AB1);
        AB1.setText("AB+");
        AB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AB1ActionPerformed(evt);
            }
        });
        getContentPane().add(AB1);
        AB1.setBounds(1170, 160, 47, 20);

        buttonGroup1.add(AB2);
        AB2.setText("AB-");
        AB2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AB2ActionPerformed(evt);
            }
        });
        getContentPane().add(AB2);
        AB2.setBounds(1170, 200, 43, 20);

        buttonGroup1.add(O2);
        O2.setText("O-");
        O2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        O2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O2ActionPerformed(evt);
            }
        });
        getContentPane().add(O2);
        O2.setBounds(1250, 200, 37, 20);

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor's Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1160, 280, 190, 310);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 18));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Buy");
        jButton1.setToolTipText("Buy from the hospital");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1250, 640, 90, 40);

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 18));
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Donate");
        jButton3.setToolTipText("Donate to the hospital");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1020, 640, 90, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel2.setText("Stock :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(960, 290, 120, 40);

        count.setEditable(false);
        getContentPane().add(count);
        count.setBounds(1060, 290, 90, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/banner1.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 0, 890, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Blood-Gel-1-High-Res-RGB-1800x1800px1.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1470, 870);

        jMenu8.setText("      File      ");
        jMenu8.setIconTextGap(10);

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/new.JPG"))); // NOI18N
        jMenuItem22.setText("New Form");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/mini.PNG"))); // NOI18N
        jMenuItem20.setText("Minimise");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/LogOff.PNG"))); // NOI18N
        jMenuItem23.setText("Log Off");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/TurnOff.PNG"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuBar4.add(jMenu8);

        jMenu3.setText("      Staff      ");
        jMenu3.setIconTextGap(10);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/add.PNG"))); // NOI18N
        jMenuItem17.setText("Add");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem14.setText("Details");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar4.add(jMenu3);

        jMenu5.setText("      Patient      ");
        jMenu5.setIconTextGap(10);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem6.setText("Search");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bill.PNG"))); // NOI18N
        jMenuItem10.setText("Billing");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar4.add(jMenu5);

        jMenu6.setText("      Doctor      ");
        jMenu6.setIconTextGap(10);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/add.PNG"))); // NOI18N
        jMenuItem18.setText("Add");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem8.setText("Search");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/appoint.PNG"))); // NOI18N
        jMenuItem11.setText("Appointments");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuBar4.add(jMenu6);

        jMenu9.setText("      Help      ");
        jMenu9.setIconTextGap(10);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/aboutus.JPG"))); // NOI18N
        jMenuItem1.setText("About Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/map.PNG"))); // NOI18N
        jMenuItem19.setText("Map");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenuBar4.add(jMenu9);

        setJMenuBar(jMenuBar4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.NewForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Default.Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int exit=(int)JOptionPane.showConfirmDialog(rootPane, "Do you want to exit?", "Hospital Management System", 0);
        if(exit==0)
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Staff.Add().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Staff.Details().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.Search().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.Billing().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Add().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Search().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Appointments().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Help.AboutUs().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        new Help.Map().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Default.Home().setVisible(true);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        donate.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buy.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            id=Integer.parseInt(pid.getText());
        }catch(Exception ex) {JOptionPane.showMessageDialog(rootPane, "Wrong Registration Number.");}
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query1="Select * from Patients where RegistrationNo="+id+";";
            ResultSet rs1=stmt.executeQuery(query1);
            if(rs1.first()==false)
            {
                JOptionPane.showMessageDialog(rootPane, "Wrong Registration Number.");
                pid.setText("");
                pname.setText("");
            } 
            else
            {
                rs1.beforeFirst();
                while(rs1.next())
                {
                    String nfind=""+rs1.getDate("DateofDischarge");
                    if(nfind.equalsIgnoreCase("null"))
                    {
                        old=rs1.getInt("Medicine");
                        if(group.getSelectedItem().equals("A+"))
                            total=500;
                        else if(group.getSelectedItem().equals("A-"))
                            total=1500;
                        else if(group.getSelectedItem().equals("B+"))
                            total=500;
                        else if(group.getSelectedItem().equals("B-"))
                            total=1000;
                        else if(group.getSelectedItem().equals("AB+"))
                            total=1000;
                        else if(group.getSelectedItem().equals("AB-"))
                            total=1500;
                        else if(group.getSelectedItem().equals("O+"))
                            total=500;
                        else if(group.getSelectedItem().equals("O-"))
                            total=1500;
                        total=total+old;
                        String query2="Update Patients set Medicine="+total+" where RegistrationNo="+id+";";
                        stmt.executeUpdate(query2);
                        JOptionPane.showMessageDialog(rootPane,"Task Completed");
                        buy.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane,"The Patient has been Discharged.","Can't Buy",0);
                        pid.setText("");
                        pname.setText("");
                    }
                }
            }
        } catch (Exception ex) {}
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dname=name.getText();
        bgroup=(String) group1.getSelectedItem();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query="Insert into Blood values('"+dname+"','"+bgroup+"');";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane,"Task Completed");
            donate.dispose();
            name.setText("");
            buttonGroup1.clearSelection();
            count.setText("");
            } catch (Exception ex) {}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='A+';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {JOptionPane.showMessageDialog(rootPane, ex);}
}//GEN-LAST:event_A1ActionPerformed

    private void O1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='O+';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {}
}//GEN-LAST:event_O1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='B+';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {}
}//GEN-LAST:event_B1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='A-';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {}
}//GEN-LAST:event_A2ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='B-';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {}
}//GEN-LAST:event_B2ActionPerformed

    private void AB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AB1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='AB+';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {}
}//GEN-LAST:event_AB1ActionPerformed

    private void AB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AB2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='AB-';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {}
}//GEN-LAST:event_AB2ActionPerformed

    private void O2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query3="Select Name from Blood where BGroup='O-';";
            ResultSet rs3=stmt.executeQuery(query3);
            model.setRowCount(0);
                    if(rs3.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry Entry Not Found.");
                    }
                    else
                    {
                        rs3.beforeFirst();
                        while(rs3.next())
                        {
                            model.addRow(new Object[] {rs3.getString("Name")});
                        }
                    }
            count.setText(""+t.getRowCount());
            } catch (Exception ex) {}
}//GEN-LAST:event_O2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A1;
    private javax.swing.JCheckBox A2;
    private javax.swing.JCheckBox AB1;
    private javax.swing.JCheckBox AB2;
    private javax.swing.JCheckBox B1;
    private javax.swing.JCheckBox B2;
    private javax.swing.JCheckBox O1;
    private javax.swing.JCheckBox O2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog buy;
    private javax.swing.JTextField count;
    private javax.swing.JDialog donate;
    private javax.swing.JComboBox group;
    private javax.swing.JComboBox group1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
