/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Doctor;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP_Owner
 */
public class Appointments extends javax.swing.JFrame {
int f=0,g=0,select,sno,h=0;
String name,date,time,dname,namep,no,doc,edic="",adsav="",old;
    /**
     * Creates new form Appointments
     */
    public Appointments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        dconsultant = new javax.swing.JComboBox();
        edican = new javax.swing.JButton();
        adsave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        jDialog1.setTitle("Input");
        jDialog1.setMinimumSize(new java.awt.Dimension(414, 166));
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialog1WindowActivated(evt);
            }
        });
        jDialog1.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("Name of the Patient");
        jDialog1.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 190, 30);
        jDialog1.getContentPane().add(pname);
        pname.setBounds(210, 40, 180, 30);

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton2);
        jButton2.setBounds(300, 100, 90, 30);

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton3);
        jButton3.setBounds(220, 100, 60, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 140, 110);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor :");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 320, 100, 30);

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "10:00"},
                {null, null, null, "10:15"},
                {null, null, null, "10:30"},
                {null, null, null, "10:45"},
                {null, null, null, "11:00"},
                {null, null, null, "11:15"},
                {null, null, null, "11:30"},
                {null, null, null, "11:45"},
                {null, null, null, "02:00"},
                {null, null, null, "02:15"},
                {null, null, null, "02:30"},
                {null, null, null, "02:45"},
                {null, null, null, "03:00"},
                {null, null, null, "03:15"},
                {null, null, null, "03:30"},
                {null, null, null, "03:45"},
                {null, null, null, "04:00"},
                {null, null, null, "04:15"},
                {null, null, null, "04:30"},
                {null, null, null, "04:45"}
            },
            new String [] {
                "Sr.No.", "Patient Name", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 370, 700, 350);

        dconsultant.setMaximumRowCount(50);
        dconsultant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------------Select--------------" }));
        dconsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dconsultantActionPerformed(evt);
            }
        });
        getContentPane().add(dconsultant);
        dconsultant.setBounds(750, 320, 170, 30);

        edican.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        edican.setForeground(new java.awt.Color(255, 0, 0));
        edican.setText("Edit");
        edican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edicanActionPerformed(evt);
            }
        });
        getContentPane().add(edican);
        edican.setBounds(1180, 440, 90, 40);

        adsave.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        adsave.setForeground(new java.awt.Color(0, 0, 204));
        adsave.setText("Add");
        adsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adsaveActionPerformed(evt);
            }
        });
        getContentPane().add(adsave);
        adsave.setBounds(1180, 580, 90, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Make_an_Appointment1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, -10, 730, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/appt.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 490, 270, 260);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/sa.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1400, 860);

        jMenu8.setText("      File      ");
        jMenu8.setIconTextGap(10);

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/new.JPG"))); // NOI18N
        jMenuItem22.setText("New Form");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/mini.PNG"))); // NOI18N
        jMenuItem20.setText("Minimise");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/LogOff.PNG"))); // NOI18N
        jMenuItem23.setText("Log Off");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/TurnOff.PNG"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuBar4.add(jMenu8);

        jMenu3.setText("      Staff      ");
        jMenu3.setIconTextGap(10);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/add.PNG"))); // NOI18N
        jMenuItem17.setText("Add");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem14.setText("Search");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar4.add(jMenu3);

        jMenu5.setText("      Patient      ");
        jMenu5.setIconTextGap(10);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem6.setText("Search");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bill.PNG"))); // NOI18N
        jMenuItem10.setText("Billing");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar4.add(jMenu5);

        jMenu6.setText("      Doctor      ");
        jMenu6.setIconTextGap(10);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/add.PNG"))); // NOI18N
        jMenuItem18.setText("Add");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem8.setText("Search");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/appoint.PNG"))); // NOI18N
        jMenuItem11.setText("Appointments");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuBar4.add(jMenu6);

        jMenu9.setText("      Help      ");
        jMenu9.setIconTextGap(10);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/aboutus.JPG"))); // NOI18N
        jMenuItem1.setText("About Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/map.PNG"))); // NOI18N
        jMenuItem19.setText("Map");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenuBar4.add(jMenu9);

        setJMenuBar(jMenuBar4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dconsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dconsultantActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        for(int i=0;i<20;i++)
        {
            model.setValueAt("", i, 1);
            model.setValueAt("", i, 0);
        }
        Object c=model.getValueAt(1, 2);
        date=c.toString();
        doc=(String) dconsultant.getSelectedItem();
        if(doc.equals("--------------Select--------------"))
        {
            JOptionPane.showMessageDialog(rootPane, "Select a Doctor");
        }
        else
        {
            try{
                Class.forName("java.sql.DriverManager");
                Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
                Statement stmt=(Statement) con.createStatement();
                String query="Select * from Appointments where DName='"+doc+"' AND Date='"+date+"';";
                ResultSet rs=stmt.executeQuery(query);
                while(rs.next())
                {
                    Object ll=rs.getTime("Time");
                    time=ll.toString();
                    for(int i=0;i<20;i++)
                    {
                        Object d=model.getValueAt(i, 3);
                        String tt=d.toString()+":00";
                        if(time.equals(tt))
                        {
                            no=""+rs.getInt("SNo");
                            model.setValueAt(no, i, 0);
                            namep=rs.getString("PName");
                            model.setValueAt(namep, i, 1);
                        }
                    }
                }
            }catch(Exception Ex){}
        }
}//GEN-LAST:event_dconsultantActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.NewForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Default.Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int exit=(int)JOptionPane.showConfirmDialog(rootPane, "Do you want to exit?", "Hospital Management System", 0);
        if(exit==0)
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Staff.Add().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Staff.Details().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.Search().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.Billing().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Add().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Search().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Appointments().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Help.AboutUs().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        new Help.Map().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if(f==0)
        {
            try {
                    f++;
                    Class.forName("java.sql.DriverManager");
                    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
                    Statement stmt=(Statement) con.createStatement();
                    String query="Select * from doctors order by name;";
                    ResultSet rs= stmt.executeQuery(query);
                    while(rs.next())
                        {
                            dconsultant.addItem(rs.getString("Name"));
                        }
                    String query2="Select curdate()";
                    ResultSet rs2=stmt.executeQuery(query2);
                    while(rs2.next())
                    {
                        DefaultTableModel m=(DefaultTableModel) t.getModel();
                        for(int i=0;i<20;i++)
                        {
                            m.setValueAt(rs2.getDate("curdate()"), i, 2);
                        }
                    }
                }
            catch (Exception ex) {}
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Default.Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        f=0;
    }//GEN-LAST:event_formWindowClosed

    private void adsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adsaveActionPerformed
        // TODO add your handling code here:
        adsav=adsave.getText();
        if(adsav.equals("Add"))
        {
            if(dconsultant.getSelectedItem()=="--------------Select--------------")
            {
               JOptionPane.showMessageDialog(rootPane, "Select a Doctor");
            }
            else
            {
                adsave.setText("Save");
                adsave.setEnabled(false);
                dconsultant.setEnabled(false);
                edican.setText("Cancel");
            }
        }
        else
        {
            if(edic.equals("Edit"))
            {
                try {
                        DefaultTableModel m=(DefaultTableModel) t.getModel();
                        Class.forName("java.sql.DriverManager");
                        Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
                        Statement stmt=(Statement) con.createStatement();
                        String query="Update Appointments set PName='"+name+"' where SNo="+m.getValueAt(select, 0)+";";
                        stmt.executeUpdate(query);
                        JOptionPane.showMessageDialog(rootPane, "Data has been Updated.", "Task Completed.", 1);
                        adsave.setText("Add");
                        dconsultant.setEnabled(true);
                        edican.setText("Edit");
                        g=0;
                        edic="";
                        adsav="";
                    }
                catch (Exception ex) {}
            }
            else
            {
                try {
                        Class.forName("java.sql.DriverManager");
                        Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
                        Statement stmt=(Statement) con.createStatement();
                        String query1="Select * from Appointments;";
                        ResultSet rs1= stmt.executeQuery(query1);
                        if(rs1.next())
                        {
                            rs1.last();
                            sno=rs1.getInt("SNo")+1;
                        }
                        else{sno=1;}
                        DefaultTableModel m=(DefaultTableModel) t.getModel();
                        Object a=m.getValueAt(select, 2);
                        Object b=m.getValueAt(select, 3);
                        date=a.toString();
                        time=b.toString();
                        dname=(String) dconsultant.getSelectedItem();
                        String query2="Insert into Appointments values("+sno+",'"+name+"','"+date+"','"+time+"','"+dname+"');";
                        stmt.executeUpdate(query2);
                        JOptionPane.showMessageDialog(rootPane, "Your id is "+sno, "Task Completed.", 1);
                        m.setValueAt(sno, select, 0);
                    }
                catch (Exception ex) {}
                adsave.setText("Add");
                g=0;
                dconsultant.setEnabled(true);
                edican.setText("Edit");
                edic="";
                adsav="";
            }
        }
}//GEN-LAST:event_adsaveActionPerformed

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        // TODO add your handling code here:
        if(adsav.equals("Add"))
            {
                DefaultTableModel m=(DefaultTableModel) t.getModel();
                select=t.getSelectedRow();
                if(m.getValueAt(select, 1).equals(""))
                {
                    if(g==0)
                    {
                        g++;
                        jDialog1.setVisible(true);
                    }
                }
            }
            else if(edic.equals("Edit"))
            {
                DefaultTableModel m=(DefaultTableModel) t.getModel();
                select=t.getSelectedRow();
                if(m.getValueAt(select, 0).toString().isEmpty()==false)
                {
                    g++;
                    old=(String)m.getValueAt(select, 1);
                    jDialog1.setVisible(true);
                }
            }
            
    }//GEN-LAST:event_tMouseClicked

    private void edicanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edicanActionPerformed
        // TODO add your handling code here:
        edic=edican.getText();
        if(edic.equals("Edit"))
        {
            if(dconsultant.getSelectedItem()=="--------------Select--------------")
            {
               JOptionPane.showMessageDialog(rootPane, "Select a Doctor");
            }
            else
            {
                adsave.setText("Save");
                dconsultant.setEnabled(false);
                adsave.setEnabled(false);
                edican.setText("Cancel");
                h++;
            }
        }
        else
        {
            if(h==1)
            {
                DefaultTableModel m=(DefaultTableModel) t.getModel();
                m.setValueAt(old, select, 1);
                adsave.setText("Add");
                adsave.setEnabled(true);
                g=0;
                edic="";
                adsav="";
                dconsultant.setEnabled(true);
                edican.setText("Edit");
                h=0;
            }
            else
            {
                DefaultTableModel m=(DefaultTableModel) t.getModel();
                m.setValueAt("", select, 1);
                adsave.setText("Add");
                adsave.setEnabled(true);
                g=0;
                edic="";
                adsav="";
                dconsultant.setEnabled(true);
                edican.setText("Edit");
            }
        }
}//GEN-LAST:event_edicanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        name=pname.getText();
        pname.setText("");
        jDialog1.dispose();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Type the Name Properly.");
            jDialog1.setVisible(true);
        }
        else{
            DefaultTableModel m=(DefaultTableModel) t.getModel();
            m.setValueAt(name, select, 1);
            adsave.setEnabled(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        g=0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDialog1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowActivated
        // TODO add your handling code here:
        jDialog1.getRootPane().setDefaultButton(jButton3);
    }//GEN-LAST:event_jDialog1WindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adsave;
    private javax.swing.JComboBox dconsultant;
    private javax.swing.JButton edican;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pname;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
