/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



package Patient;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.print.PrinterException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP_Owner
 */
public class Search extends javax.swing.JFrame {
    static String room,consultant;
    static int temp=0,a;
String x,y,id,b,c;
int row,change=0;
    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        print = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        page = new javax.swing.JTextField();
        psex = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        proom = new javax.swing.JTextField();
        printbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pconsultant = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pproblem = new javax.swing.JTextArea();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        print.setFont(new java.awt.Font("Rockwell", 0, 14));
        print.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(print);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Registration no.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(960, 50, 190, 22);

        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        getContentPane().add(s2);
        s2.setBounds(1090, 130, 240, 35);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(670, 0, 10, 750);

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration no.", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(860, 220, 452, 402);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel2.setText("Enter Name to Search");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(870, 140, 180, 22);

        s1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                s1CaretUpdate(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(260, 120, 270, 35);

        jLabel3.setFont(new java.awt.Font("Rockwell", 2, 30));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Registration no. to Search");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 52, 460, 40);

        edit.setFont(new java.awt.Font("Rockwell", 0, 18));
        edit.setForeground(new java.awt.Color(255, 0, 0));
        edit.setText("Edit");
        edit.setEnabled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(230, 660, 65, 50);

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 220, 70, 30);

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Age");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 280, 60, 30);

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sex");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 340, 60, 30);

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Problem");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 430, 90, 30);

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Room no.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 540, 100, 30);

        page.setEditable(false);
        page.setFont(new java.awt.Font("Monospaced", 1, 14));
        getContentPane().add(page);
        page.setBounds(360, 280, 200, 30);

        psex.setEditable(false);
        psex.setFont(new java.awt.Font("Monospaced", 1, 14));
        getContentPane().add(psex);
        psex.setBounds(360, 340, 200, 30);

        pname.setEditable(false);
        pname.setFont(new java.awt.Font("Monospaced", 1, 14));
        getContentPane().add(pname);
        pname.setBounds(360, 220, 200, 30);

        proom.setEditable(false);
        proom.setFont(new java.awt.Font("Monospaced", 1, 14));
        getContentPane().add(proom);
        proom.setBounds(360, 540, 200, 30);

        printbtn.setFont(new java.awt.Font("Rockwell", 0, 18));
        printbtn.setForeground(new java.awt.Color(51, 0, 255));
        printbtn.setText("Print");
        printbtn.setToolTipText("Prints all the details.");
        printbtn.setEnabled(false);
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        getContentPane().add(printbtn);
        printbtn.setBounds(470, 660, 110, 50);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 140, 110);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 18));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Consultant");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 600, 130, 30);

        pconsultant.setEditable(false);
        pconsultant.setFont(new java.awt.Font("Monospaced", 1, 14));
        getContentPane().add(pconsultant);
        pconsultant.setBounds(360, 600, 200, 30);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pproblem.setColumns(20);
        pproblem.setEditable(false);
        pproblem.setFont(new java.awt.Font("Monospaced", 1, 14));
        pproblem.setLineWrap(true);
        pproblem.setRows(5);
        pproblem.setWrapStyleWord(true);
        jScrollPane2.setViewportView(pproblem);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(360, 400, 200, 110);

        jMenu8.setText("      File      ");
        jMenu8.setIconTextGap(10);

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/new.JPG"))); // NOI18N
        jMenuItem22.setText("New Form");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/mini.PNG"))); // NOI18N
        jMenuItem20.setText("Minimise");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/LogOff.PNG"))); // NOI18N
        jMenuItem23.setText("Log Off");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/TurnOff.PNG"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuBar4.add(jMenu8);

        jMenu3.setText("      Staff      ");
        jMenu3.setIconTextGap(10);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/add.PNG"))); // NOI18N
        jMenuItem17.setText("Add");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem14.setText("Search");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar4.add(jMenu3);

        jMenu5.setText("      Patient      ");
        jMenu5.setIconTextGap(10);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem6.setText("Search");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bill.PNG"))); // NOI18N
        jMenuItem10.setText("Billing");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar4.add(jMenu5);

        jMenu6.setText("      Doctor      ");
        jMenu6.setIconTextGap(10);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/add.PNG"))); // NOI18N
        jMenuItem18.setText("Add");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/search.PNG"))); // NOI18N
        jMenuItem8.setText("Search");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/appoint.PNG"))); // NOI18N
        jMenuItem11.setText("Appointments");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuBar4.add(jMenu6);

        jMenu9.setText("      Help      ");
        jMenu9.setIconTextGap(10);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/aboutus.JPG"))); // NOI18N
        jMenuItem1.setText("About Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/map.PNG"))); // NOI18N
        jMenuItem19.setText("Map");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenuBar4.add(jMenu9);

        setJMenuBar(jMenuBar4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        a=Integer.parseInt(s1.getText());
        room=proom.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from Patients where RegistrationNo="+a+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next())
            {
                int rm=rs.getInt("RoomNo");
                if(rm==1)
                {

                    String query3="Select * from Rooms where Accommodated='Yes' And RoomNo="+rm+" order by bedno desc;";
                    ResultSet rs3=stmt.executeQuery(query3);
                    rs3.next();
                    String query5="Update Rooms set Accommodated='No' where RoomNo="+rm+" And BedNo="+rs3.getInt("BedNo")+";";
                    stmt.executeUpdate(query5);
                }
                else if(rm==2)
                {
                    String query3="Select * from Rooms where Accommodated='Yes' And RoomNo="+rm+" order by bedno desc;";
                    ResultSet rs3=stmt.executeQuery(query3);
                    rs3.next();
                    String query5="Update Rooms set Accommodated='No' where RoomNo="+rm+" And BedNo="+rs3.getInt("BedNo")+";";
                    stmt.executeUpdate(query5);
                }
                else if(rm==3)
                {
                    String query3="Select * from Rooms where Accommodated='Yes' And RoomNo="+rm+" order by bedno desc;";
                    ResultSet rs3=stmt.executeQuery(query3);
                    rs3.next();
                    String query5="Update Rooms set Accommodated='No' where RoomNo="+rm+" And BedNo="+rs3.getInt("BedNo")+";";
                    stmt.executeUpdate(query5);
                }
                else if(rm==4)
                {
                    String query3="Select * from Rooms where Accommodated='Yes' And RoomNo="+rm+" order by bedno desc;";
                    ResultSet rs3=stmt.executeQuery(query3);
                    rs3.next();
                    String query5="Update Rooms set Accommodated='No' where RoomNo="+rm+" And BedNo="+rs3.getInt("BedNo")+";";
                    stmt.executeUpdate(query5);
                }
                else
                {
                    String query5="Update Rooms set Accommodated='No' where RoomNo="+rm+";";
                    stmt.executeUpdate(query5);
                }
            }
            } catch (Exception ex) {}
        consultant=pconsultant.getText();
        temp++;
        this.dispose();
        new NewForm().setVisible(true);
}//GEN-LAST:event_editActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
        x=s2.getText();
        DefaultTableModel model=(DefaultTableModel) t.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query="Select * from Patients where Name like'"+x+"%' order by RegistrationNo Asc;";
            ResultSet rs= stmt.executeQuery(query);
            model.setRowCount(0);
                    if(rs.first()==false)
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry entry not found");
                    }
                    else
                    {
                        rs.beforeFirst();
                        while(rs.next())
                        {
                            String id1=rs.getString("RegistrationNo");
                            String tname=rs.getString("Name");
                            model.addRow(new Object[] {id1,tname});
                        }
                    }
        } catch (Exception ex) {}
    }//GEN-LAST:event_s2ActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t=(DefaultTableModel) print.getModel();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query1="Select * from Patients where RegistrationNo="+Integer.parseInt(y)+";";
            ResultSet rs= stmt.executeQuery(query1);
            t.setRowCount(0);
            while(rs.next())
            {
            for(int i=0;i<=18;i++)
                 {
                    switch(i)
                    {
                        case 0:c="RegistrationNo";
                               b=rs.getString("RegistrationNo");
                               break;
                        case 1:c="Room No.";
                               b=rs.getString("RoomNo");
                               break;
                        case 2:c="Name";
                               b=rs.getString("Name");
                               break;
                        case 3:c="Age";
                               b=rs.getString("Age");
                               break;
                        case 4:c="Sex";
                               b=rs.getString("Sex");
                               break;
                        case 5:c=rs.getString("Relation");
                               b=rs.getString("RelativeName");
                               break;
                        case 6:c="Address";
                               b=rs.getString("Address");
                               break;
                        case 7:c="Phone No.";
                               b=rs.getString("PhoneNo");
                               break;
                        case 8:c="Consultant";
                               b=rs.getString("Consultant");
                               break;
                        case 9:c="Problem";
                               b=rs.getString("Problem");
                               break;
                        case 10:c="Date of Admission";
                               b=rs.getString("DateofAdmission");
                               break;
                        case 11:c="Time of Admission";
                               b=rs.getString("TimeofAdmission");
                               break;
                        case 12:c="Date of Discharge";
                               b=rs.getString("DateofDischarge");
                               break;
                        case 13:c="Time of Discharge";
                               b=rs.getString("TimeofDischarge");
                               break;
                        case 14:c="Place of Accident";
                               b=rs.getString("PlaceofAccident");
                               break;
                        case 15:c="Detail of Accident";
                               b=rs.getString("DetailofAccident");
                               break;
                        case 16:c="Allergies";
                               b=rs.getString("Allergies");
                               break;
                        case 17:c="Occupation";
                               b=rs.getString("Occupation");
                               break;
                        case 18:c="Habit";
                               b=rs.getString("AnyHabit");
                               break;
                        default:;
                    }
                       t.addRow(new Object[] {c,b});
                 }}
        } catch (Exception ex) {}
        try {
                print.print();
            }
            catch (PrinterException ex) {ex.printStackTrace();}
}//GEN-LAST:event_printbtnActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new NewForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Default.Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int exit=(int)JOptionPane.showConfirmDialog(rootPane, "Do you want to exit?", "Hospital Management System", 0);
        if(exit==0)
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Staff.Add().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Staff.Details().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.Search().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Patient.Billing().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Add().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Search().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Doctor.Appointments().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Help.AboutUs().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        new Help.Map().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
               this.dispose();
        new Default.Home().setVisible(true);
  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        // TODO add your handling code here:
        row=t.getSelectedRow();
        DefaultTableModel model2=(DefaultTableModel) t.getModel();
        try {
            change++;
            id=(String)model2.getValueAt((row),0);
            s1.setText(id);
            printbtn.setEnabled(true);
        } catch (Exception ex) {}
    }//GEN-LAST:event_tMouseClicked

    private void s1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_s1CaretUpdate
        // TODO add your handling code here:
        if(change!=0)
        {
        y=s1.getText();
        if(y.isEmpty()||y.contains(" "))
         ;
        else
        {
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query1="Select * from Patients where RegistrationNo="+Integer.parseInt(y)+";";
            ResultSet rs1= stmt.executeQuery(query1);
            while(rs1.next())
            {
                    pname.setText(rs1.getString("Name"));
                    page.setText(rs1.getString("Age"));
                    psex.setText(rs1.getString("Sex"));
                    pproblem.setText(rs1.getString("Problem"));
                    proom.setText(rs1.getString("RoomNo"));
                    pconsultant.setText(rs1.getString("Consultant"));
                    String discharge=""+rs1.getDate("DateofDischarge");
                    if(discharge.equalsIgnoreCase("null"))
                    {
                        edit.setEnabled(true);
                    }
                    else
                    {
                        edit.setEnabled(false);
                    }
                    change=0;
            }
        } catch (Exception ex) {}}}
    }//GEN-LAST:event_s1CaretUpdate

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
        y=s1.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aionix","root","");
            Statement stmt=(Statement) con.createStatement();
            String query1="Select * from Patients;";
            ResultSet rs1= stmt.executeQuery(query1);
            while(rs1.next())
                {
                    if(rs1.getString("RegistrationNo").equals(y.trim()))
                    {
                        pname.setText(rs1.getString("Name"));
                        page.setText(rs1.getString("Age"));
                        psex.setText(rs1.getString("Sex"));
                        pproblem.setText(rs1.getString("Problem"));
                        proom.setText(rs1.getString("RoomNo"));
                        pconsultant.setText(rs1.getString("Consultant"));
                        printbtn.setEnabled(true);
                        String discharge=""+rs1.getDate("DateofDischarge");
                        if(discharge.equalsIgnoreCase("null"))
                        {
                            edit.setEnabled(true);
                        }
                        else
                        {
                            edit.setEnabled(false);
                        }
                        break;
                    }
                    else if(rs1.isLast())
                    {
                        JOptionPane.showMessageDialog(rootPane,"Sorry entry not found");
                    }
                }
        } catch (Exception ex) {}
    }//GEN-LAST:event_s1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField page;
    private javax.swing.JTextField pconsultant;
    private javax.swing.JTextField pname;
    private javax.swing.JTextArea pproblem;
    private javax.swing.JTable print;
    private javax.swing.JButton printbtn;
    private javax.swing.JTextField proom;
    private javax.swing.JTextField psex;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
